// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUserByUnqiueID(ctx context.Context, arg DeleteUserByUnqiueIDParams) (User, error)
	DeleteUsers(ctx context.Context, arg DeleteUsersParams) ([]User, error)
	GetAll(ctx context.Context, arg GetAllParams) ([]User, error)
	GetUserByUnqiueID(ctx context.Context, arg GetUserByUnqiueIDParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
}

var _ Querier = (*Queries)(nil)
